config/routes.rb
Rails.application.routes.draw do
  
  root    'pages#home'
  get     '/pages/home'       =>    'pages#home'
  get     '/dishes'           =>    'dishes#index'
  get     '/dishes/show/:id'  =>    'dishes#show'
  get     '/dishes/show'      =>    'dishes#show'
  devise_for :admins
  devise_for :users

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :dishes
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
end

app/models/cost.rb
class Cost < ActiveRecord::Base
	has_many :dishes
end

app/models/country.rb
class Country < ActiveRecord::Base
	has_many :dishes
end

app/models/difficulty.rb
class Difficulty < ActiveRecord::Base
	has_many :dishes
end

app/models/dish.rb
class Dish < ActiveRecord::Base
	belongs_to :cost
	belongs_to :difficulty
	belongs_to :country
	belongs_to :category
	has_many :posts
	has_one :recipe
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
	has_many :ingredient_recipes
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	belongs_to :dish
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	belongs_to :dish
	has_many :ingredients, through: :ingredient_recipes
	has_many :unities, through: :ingredient_recipes
end

app/models/unity.rb
class Unity < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts, :dependent => :destroy
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/costs_helper.rb
module CostsHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/unities_helper.rb
module UnitiesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer-basic-centered">
	<p class="footer-company-motto">Cooking mamamia</p>
		<p class="footer-links">
			<a href="#">Home</a>
			·
			<a href="#">About</a>
			·
			<a href="#">Faq</a>
			·
			<a href="#">Contact</a>
		</p>
	<p class="footer-company-name">Cooking mamamia &copy; 2015</p>
</footer>

app/views/layouts/_form.html.erb
<div class="formulaire_recettes">
	<h1 id="center_titre_recettes">Recettes</h1>

	<p id="center_texte_recettes"> En manque d’idées menu ? Apéritifs, entrées, plats, desserts, boissons… Cookingmamamia vous propose, gratuitement, près de 4 000 recettes. A vos fourneaux ! </p>
	
	<hr class="featurette-divider" id="line-separator-recettes">

	<div class="row">
		<div class="col-md-4">Recettes <%= Category.find(1).name.downcase %></div>
		<div class="col-md-4">Recettes <%= Category.find(2).name.downcase %></div>
		<div class="col-md-4">Recettes <%= Category.find(3).name.downcase %></div>
	</div>

	<div class="row">
		<div class="col-md-4">Recettes <%= Category.find(4).name.downcase %></div>
		<div class="col-md-4">Recettes <%= Category.find(5).name.downcase %></div>
		<div class="col-md-4">Recettes <%= Category.find(6).name.downcase %></div>
	</div>
	Recettes <%= Category.find(6).name.downcase %>
	<hr class="featurette-divider" id="line-separator-recettes-2">
	
	<div class="well">
		<h1>Rechercher une recette</h1>
		<form id="formulaire_recettes">

		 	<div class = "form-group">
		      <label for = "name">Type de plat :</label>
				<select class="form-control">
	      			<% @categories.each do |categorie| %>
	       					<option><%= categorie.name %></option>
	       			<% end %>
      			</select>
		   </div>
		   <div class="row">
		   		<div class="col-md-4">
		   			<div class = "checkbox">
		   				Difficulté:
			      		<label class="checkbox-inline"><input type = "checkbox">
							<span class="glyphicon glyphicon-star" aria-hidden="true"></span>
			      		</label>
			      		<label class="checkbox-inline"><input type = "checkbox">
							<span class="glyphicon glyphicon-star" aria-hidden="true"></span>
							<span class="glyphicon glyphicon-star" aria-hidden="true"></span>
			      		</label>
			      		<label class="checkbox-inline"><input type = "checkbox">
			      			<span class="glyphicon glyphicon-star" aria-hidden="true"></span>
			      			<span class="glyphicon glyphicon-star" aria-hidden="true"></span>
			      			<span class="glyphicon glyphicon-star" aria-hidden="true"></span>
			      		</label>
			   		</div>
		   		</div>
		   		<div class="col-md-4">
		   			<div class = "checkbox">
		   				Budget:
			      		<label class="checkbox-inline"><input type = "checkbox">
							<span class="glyphicon glyphicon-euro" aria-hidden="true"></span>
			      		</label>
			      		<label class="checkbox-inline"><input type = "checkbox">
							<span class="glyphicon glyphicon-euro" aria-hidden="true"></span>
							<span class="glyphicon glyphicon-euro" aria-hidden="true"></span>
			      		</label>
			      		<label class="checkbox-inline"><input type = "checkbox">
			      			<span class="glyphicon glyphicon-euro" aria-hidden="true"></span>
			      			<span class="glyphicon glyphicon-euro" aria-hidden="true"></span>
			      			<span class="glyphicon glyphicon-euro" aria-hidden="true"></span>
			      		</label>
			   		</div>
		   		</div>
		   		<div class="col-md-4">
		   			<button type = "submit" class = "btn btn-default">Rechercher	</button>
		   		</div>
		   </div> 
		</form>
	</div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Cooking mamamia</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <form class="navbar-form navbar-right">
            <% if user_signed_in? %>
              <<!-- button type="submit" class="btn btn-success">Se connecter</button> -->
              Connecté en tant que <strong><%= current_user.email %></strong>.
              <%= link_to "Editer profil", edit_user_registration_path, class: "btn btn-warning" %>
              <%= link_to "Se déconnecter", destroy_user_session_path, class: "btn btn-danger" %>
            <% else %>
              <%= link_to "Se connecter",  new_user_session_path , class: "btn btn-success" %>
              <%= link_to "S'inscrire", new_user_registration_path , class: "btn btn-info" %>
            <% end %>
          </form>
        </div><!--/.navbar-collapse -->
      </div>
</nav>
<div class="jumbotron" id="jumbo">
  <div class="container text-center">
    <h1>Recettes de cuisine</h1>
    <p class = "text-info">Recettes de saison, recettes par pays... Des inspirations pour toutes les envies !</p>
    <p><%= link_to "Nos recettes >>", dishes_path , class: "btn btn-primary btn-lg" %></p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= titre %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

  </head>
  <body>
    
    <%= render "layouts/header"%>
      <% if notice %>
        <p class="alert alert-success">
          <%= notice %>
        </p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger">
          <%= alert %>
        </p>
      <% end %>
      <%= yield %>
    <%= render "layouts/footer"%>

  </body>
</html>

app/views/pages/home.html.erb
 
    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->
  
      <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner" role="listbox">

            <div class="item active">
              <div class="container">
                <div class="carousel-caption">
                  

                  <!-- Three columns of text below the carousel -->
                <div class="row">
                  <div class="col-lg-4">
                    <img src="/assets/countries_flags/france.png" alt="Generic placeholder image" width="140" height="140">
                    <h2>Heading</h2>
                    <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.</p>
                    <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
                  </div><!-- /.col-lg-4 -->
                  <div class="col-lg-4">
                    <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
                    <h2>Heading</h2>
                    <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.</p>
                    <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
                  </div><!-- /.col-lg-4 -->
                  <div class="col-lg-4">
                    <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
                    <h2>Heading</h2>
                    <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
                    <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
                  </div><!-- /.col-lg-4 -->
                </div><!-- /.row -->


                </div>
              </div>
            </div>

              <!-- Boucle FOR pour afficher les icones des pays -->
              <% for i in 1 .. 5
                        j = 4
                        loop do
              %>

                      <div class="item">
                        <div class="container">
                          <div class="carousel-caption">
                            <div class="row">
                      <%
                          for k in j .. j+2
                      %>

                            
                              <div class="col-lg-4">
                                <%  
                                    source = "àâçèéêîôùû"
                                    dest= "aaceeeiouu"
                                    chaine = Country.find(k).name
                                    chaine = chaine.downcase
                                    chaine = chaine.tr(source, dest)
                                    chaine = chaine.gsub(/([\s\'\-])/, '_')
                                %>
                                <img src="/assets/countries_flags/<%= chaine %>.png" alt="Generic placeholder image" width="140" height="140">
                                <h2><%= Country.find(k).name %></h2>
                                <p><%= Country.find(k).description %></p>
                                <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
                              </div><!-- /.col-lg-4 -->
                      <%
                          end
                          j += 3
                      %>
                            </div><!-- /.row -->
                          </div>
                        </div>
                      </div>
                      <%
                          break if j > 21
                        end
                      %>
              <% end %>

        </div>

        <!-- LEFT BUTTON -->
        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left" aria-hidden="true" style="color:red"></span>
          <span class="sr-only">Previous</span>
        </a>
        <!-- RIGHT BUTTON -->
        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true" style="color:red"></span>
          <span class="sr-only">Next</span>
        </a>

      </div>


<hr class="featurette-divider" id="line-separator">
<h1 id="recettes">Quelques recettes</h1>
<hr class="featurette-divider" id="divider-test">

<div class="container">

      <!-- START THE FEATURETTES -->

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">First featurette heading. <span class="text-muted">It'll blow your mind.</span></h2>
          <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>
        <div class="col-md-5">
          <img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7 col-md-push-5">
          <h2 class="featurette-heading">Oh yeah, it's that good. <span class="text-muted">See for yourself.</span></h2>
          <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>
        <div class="col-md-5 col-md-pull-7">
          <img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">And lastly, this one. <span class="text-muted">Checkmate.</span></h2>
          <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>
        <div class="col-md-5">
          <img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
        </div>
      </div>

      <hr class="featurette-divider">

      <!-- /END THE FEATURETTES -->
</div>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Tealeaf Todo</a>
    </div>
  </div>
</nav>